#!/bin/bash

OSTACKLAB=openstack_kolla_ansible_2024_1_no_swift.xml
sudo vnx -f $OSTACKLAB -v --shutdown

SCENARIO='openstack_kolla_openstack'
VNXDIR=$( sudo vnx -V | grep "VNX dir" | cut -d "=" -f 2 | sed -e "s,~,${HOME}," )
BASEIMG='/usr/share/vnx/filesystems/vnx_rootfs_kvm_ubuntu64-22.04-v025.qcow2'

echo "--"
echo "-- Consolidating vm images of scenario '$SCENARIO'"
echo "--   BASEIMG = $BASEIMG"
echo "--   VNXDIR  = $VNXDIR"

VMS="controller network compute1 compute2 compute3 tf-node"
cd filesystems3/

for VMNAME in $VMS; do

  NEWIMG="vnx_rootfs_kvm_ubuntu64-22.04-v025-ostack-$VMNAME.qcow2"

  echo "--"
  echo "-- Creating consolidated image for vm '$VMNAME'..."
  echo "--   NEWIMG  = $NEWIMG"
  # Delete existing image (in case it exists)
  sudo rm -f $NEWIMG
  # Copy base rootfs image
  sudo cp -v $BASEIMG $NEWIMG
  # Copy vm diff image
  sudo cp -v $VNXDIR/scenarios/$SCENARIO/vms/$VMNAME/fs/root_cow_fs tmp-diff-$VMNAME.qcow2
  ls -lh $BASEIMG tmp-diff-$VMNAME.qcow2
  # Merge diff image with new image
  sudo qemu-img rebase -F qcow2 -b $NEWIMG tmp-diff-$VMNAME.qcow2
  sudo qemu-img commit tmp-diff-$VMNAME.qcow2
  sudo rm tmp-diff-$VMNAME.qcow2
  sudo rm -f rootfs_ostack_$VMNAME
  sudo ln -s $NEWIMG rootfs_ostack_$VMNAME
  sudo chown $USER.$USER $NEWIMG rootfs_ostack_$VMNAME

done