#!/bin/bash

START_TIME=$SECONDS

function pak { 
  if [ ! -z "$PAUSE"  ]; then
    read -p "Press any key to continue..."; 
  fi
}

function msg () { 
  echo "--"
  echo "-- $1"
  echo "--" 
}

if [[ "$1" == "-p" ]]; then PAUSE="yes"; fi

ALL='controller compute1 compute2 compute3'

for m in $ALL; do 
  msg "Testing conectivity to $m"
  echo ssh root@${m} w
  ssh root@${m} w
done
pak

for m in $ALL; do 

  msg "Initial configuration of $m"
  pak
  ssh root@${m} "
      sed -i '/swap/d' /etc/fstab
      swapoff -a
      echo 'overlay' >> /etc/modules-load.d/containerd.conf
      echo 'br_netfilter' >> /etc/modules-load.d/containerd.conf
      modprobe overlay
      modprobe br_netfilter

      echo 'net.bridge.bridge-nf-call-ip6tables = 1' >> /etc/sysctl.d/kubernetes.conf
      echo 'net.bridge.bridge-nf-call-iptables = 1' >> /etc/sysctl.d/kubernetes.conf
      echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.d/kubernetes.conf

      sysctl --system
  "
  #pak

  msg "Step 3) Install containerd run time"
  echo ssh root@${m} 'apt install -y curl gnupg2 software-properties-common apt-transport-https ca-certificates'
  ssh root@${m} 'DEBIAN_FRONTEND=noninteractive apt install -y curl gnupg2 software-properties-common apt-transport-https ca-certificates'
  #pak

  # No es necesario, ya esta instalado el repositorio de docker 
  #echo ssh root@${m} 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg  --dearmor | tee /etc/apt/trusted.gpg.d/docker.gpg > /dev/null'
  ##ssh root@${m} 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg'
  ## See: https://gist.github.com/notpushkin/1cbdd3cbab0cf3570f87b7f2c0cb852d
  #ssh root@${m} 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg  --dearmor | tee /etc/apt/trusted.gpg.d/docker.gpg > /dev/null'
  #pak

  #echo ssh root@${m} 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
  #ssh root@${m} 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
  #pak

  #echo ssh root@${m} 'apt update'
  #ssh root@${m} 'apt update'
  #pak

  #echo ssh root@${m} 'apt install -y containerd.io'
  #ssh root@${m} 'apt install -y containerd.io'
  #pak

  echo ssh root@${m} 'containerd config default | tee /etc/containerd/config.toml >/dev/null 2>&1'
  ssh root@${m} 'containerd config default | tee /etc/containerd/config.toml >/dev/null 2>&1'
  #pak

  echo ssh root@${m} "sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml"
  ssh root@${m} "sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml"
  #pak

  echo ssh root@${m} 'systemctl restart containerd'
  ssh root@${m} 'systemctl restart containerd'
  #pak

  echo ssh root@${m} 'systemctl enable containerd'
  ssh root@${m} 'systemctl enable containerd'
  #pak

done

for m in $ALL; do 

  msg "Step 4) Add apt repository for Kubernetes ($m)"
  ssh root@${m} "
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg > /dev/null
      echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

      # Deprecated (https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)
      # curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | tee /etc/apt/trusted.gpg.d/k8s.gpg > /dev/null
      ##curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      #apt-add-repository 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
  "
  msg "Step 5) Install Kubernetes components Kubectl, kubeadm & kubelet ($m)"
  ssh root@${m} "
      apt update
      apt install -y kubelet kubeadm kubectl
      apt-mark hold kubelet kubeadm kubectl
  "
#  msg "Step 4/5) Install Kubernetes components Kubectl, kubeadm & kubelet ($m) as snap packages"
#  ssh root@${m} "
#      snap install kubectl --classic
#      snap install kubeadm --classic
#      snap install kubelet --classic
#      apt install critcl
#  "
  pak

done


msg "Step 6) Initialize Kubernetes cluster with Kubeadm command (controller)"
msg "  Downloading images..."
pak
ssh root@controller "kubeadm config images pull"
msg "  Executing kubeadm init on master node..."
ssh root@controller "
  echo 1 > /proc/sys/net/ipv4/ip_forward
  kubeadm init --control-plane-endpoint=10.0.0.11

  mkdir -p \$HOME/.kube
  cp -i /etc/kubernetes/admin.conf \$HOME/.kube/config
  chown \$(id -u):\$(id -g) \$HOME/.kube/config
  kubectl cluster-info
  kubectl get nodes
"
pak

JOINCMD=$( ssh root@controller "kubeadm token create --print-join-command" )
echo $JOINCMD
pak

msg "Adding compute1..."
ssh root@compute1 "
  echo 1 > /proc/sys/net/ipv4/ip_forward
  $JOINCMD
"
pak

msg "Adding compute2..."
ssh root@compute2 "
  echo 1 > /proc/sys/net/ipv4/ip_forward
  $JOINCMD
"
#ssh root@compute2 "$JOINCMD"
pak

msg "Adding compute3..."
ssh root@compute3 "
  echo 1 > /proc/sys/net/ipv4/ip_forward
  $JOINCMD
"
#ssh root@compute3 "$JOINCMD"
pak

ssh root@controller "kubectl get nodes"
pak

msg "Step 6) Install Calico Pod Network Add-on"
#  curl https://projectcalico.docs.tigera.io/manifests/calico.yaml -O
#  kubectl apply -f calico.yaml
ssh root@controller "
  kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
  kubectl set env daemonset/calico-node -n kube-system  IP_AUTODETECTION_METHOD=interface=eth1
"

sleep 30
ssh root@controller "kubectl get pods -n kube-system"
pak

msg "Step 7) Install Multus"
ssh root@controller "
    mkdir -p k8s
    cd k8s
    git clone https://github.com/k8snetworkplumbingwg/multus-cni.git
    cd multus-cni
    cat ./deployments/multus-daemonset-thick.yml | kubectl apply -f -
    sleep 10
    kubectl get pods --all-namespaces | grep -i multus
"
pak

msg "Step 8) Install Ingress NGINX"
ssh root@controller "
    cd k8s/
    wget https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.5.1/deploy/static/provider/baremetal/deploy.yaml
    sed -i 's/NodePort/LoadBalancer/' deploy.yaml
    kubectl apply -f deploy.yaml
    kubectl get pods -n ingress-nginx
"
pak

msg "Step 9) Install MetalLB"
scp -r conf/k8s/metallb/* root@controller:k8s/
ssh root@controller "
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
    sleep 20
    kubectl apply -f k8s/config-pool.yaml
    kubectl apply -f k8s/config-l2adv.yaml
    kubectl get all -n metallb-system
"

scp -r conf/k8s/examples/ root@controller:

ELAPSED_TIME=$(($SECONDS - $START_TIME))
echo "--"
echo "-- K8s installed in $ELAPSED_TIME seconds"
echo "--"

