heat_template_version: wallaby
description: Example auto scale group, policy and alarm
resources:
  instance_group:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 10
      desired_capacity: 1
      min_size: 1
      max_size: 3
      resource:
        type: OS::Nova::Server::MyServer
        properties:
          metadata: {"metering.server_group": {get_param: "OS::stack_id"}}

  scaleout_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: instance_group }
      cooldown: 10
      scaling_adjustment: 1

  scalein_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: instance_group }
      cooldown: 10
      scaling_adjustment: -1

  cpu_alarm_high:
    type: OS::Aodh::GnocchiAggregationByResourcesAlarm
    properties:
      description: Scale up if CPU > 70%
      metric: cpu_util
      aggregation_method: sum
      granularity: 60
      evaluation_periods: 1
      threshold: 80.0 # Uso de CPU del 70% - Threshold = 10⁹ x Granularity x Percentage
      resource_type: instance
      comparison_operator: gt
      alarm_actions:
        - str_replace:
            template: trust+url
            params:
              url: {get_attr: [scaleout_policy, signal_url]}
      query:
        str_replace:
          template: '{"=": {"server_group": "stack_id"}}'
          params:
            stack_id: {get_param: "OS::stack_id"}

  cpu_alarm_low:
    type: OS::Aodh::GnocchiAggregationByResourcesAlarm
    properties:
      description: Scale down if CPU < 20%
      metric: cpu
      aggregation_method: rate:mean
      granularity: 60
      evaluation_periods: 2
      threshold: 200000000.0 # Uso de CPU del 20% 
      resource_type: instance
      comparison_operator: lt
      alarm_actions:
        - str_replace:
            template: trust+url
            params:
              url: {get_attr: [scalein_policy, signal_url]}
      query:
        str_replace:
          template: '{"=": {"server_group": "stack_id"}}'
          params:
            stack_id: {get_param: "OS::stack_id"}

outputs:
  scaleout_policy_signal_url:
    description: "La URL a la que mandar la senal para activar el autoescalado hacia arriba"
    value: {get_attr: [scaleout_policy, signal_url]}
    
  scalein_policy_signal_url:
    description: "La URL a la que mandar la senal para activar el autoescalado hacia arriba"
    value: {get_attr: [scalein_policy, signal_url]}

  current_size:
    description: "El numero actual de servidores en el AutoScalingGroup"
    value: {get_attr: [instance_group, current_size]}

