heat_template_version: 2017-02-24

description: Plantilla de Heat para desplegar servidores extra en el escenario, permitiendo autoescalado.

resources:
  
  scaling_group:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 0
      max_size: 6
      desired_capacity: 1
      resource:
        type: OS::Nova::Server
        properties:
          flavor: m1.large
          image: focal-servers-vnx
          security_groups:
          - open
          networks: 
          - network: net1
            fixed_ip: 10.1.1.90
            subnet: subnet1
          - network: net2
            subnet: subnet2
          user_data_format: RAW
          user_data: |
            #!/bin/bash
            systemctl start apache2
            echo "<h1>Bienvenidos a un Servidor Extra</h1>" > /var/www/html/index.html
  
  lb_memberSExtra:
    type: OS::Octavia::PoolMember
    properties:
      pool: lb_pool
      protocol_port: 80
      address: 10.1.1.90

  scaling_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      scaling_adjustment: 1  # Agregar una instancia
      auto_scaling_group_id: {get_resource: scaling_group}
      cooldown: 60
  
  cpu_alarm_high:
    type: OS::Aodh::GnocchiAggregationByResourcesAlarm
    properties:
      description: Scale up if CPU > 1%
      metric: cpu_util
      aggregation_method: mean
      granularity: 20
      evaluation_periods: 3
      threshold: 1
      resource_type: instance
      comparison_operator: gt
      alarm_actions:
        - str_replace:
            template: trust+url
            params:
              url: {get_attr: [scaling_policy, signal_url]}
      query:
        str_replace:
          template: '{"=": {"server_group": "stack_id"}}'
          params:
            stack_id: {get_param: "OS::stack_id"}
    


          

