heat_template_version: wallaby
description: Template to spawn a server and a LB member every time there is a scale_up.

parameters:
  metadata:
    type: json
  flavor:
    type: string
    description: instance flavor to be used
    default: m1.large
  image:
    type: string
    description: instance image to be used
    default: focal-servers-vnx
  network1:
    type: string
    description: project network to attach instance to
    default: Net1
  network2:
    type: string
    description: internal project network to attach instance to
    default: Net2
  security_group:
    type: string
    description: security group of the instance
    default: open
  lb_pool:
    type: string
    description: LB pool where the servers are attached to
    default: lb_pool
  # indice:
  #   type: number
  #   description: Index to create unique resource names
  #   constraints:
  #     - modulo: { step: 1, offset: 0 }

resources:
  server:
    type: OS::Nova::Server
    properties:
      # name: {get_param: indice} 
      image: {get_param: image}
      flavor: {get_param: flavor}
      metadata: {get_param: metadata}
      networks:
        - port: {get_resource: port1}
        - port: {get_resource: port2}
      key_name: s1
      user_data_format: RAW
      user_data: |
        #!/bin/bash
        systemctl start apache2
        echo "<h1>Bienvenidos a un Servidor Extra</h1>" > /var/www/html/index.html
  
  lb_member:
    type: OS::Octavia::PoolMember
    properties:
      pool: {get_param: lb_pool}
      protocol_port: 80
      address: {get_attr: [port1, fixed_ips, 0, ip_address]}

  port1:
    type: OS::Neutron::Port
    properties:
      network: {get_param: network1}
      security_groups:
        - {get_param: security_group}
  
  port2:
    type: OS::Neutron::Port
    properties:
      network: {get_param: network2}
      security_groups: 
        - {get_param: security_group}