#!/bin/bash

if [ ! -z "$1" ]; then
    INVENTORY="/root/kolla/share/kolla-ansible/ansible/inventory/multinode-$1"
else
    INVENTORY="/root/kolla/share/kolla-ansible/ansible/inventory/multinode"
fi

source /root/kolla/bin/activate

# Añadido por Pablo. Generar certificados de Octavia
kolla-ansible octavia-certificates 

kolla-ansible -i $INVENTORY --configdir /etc/kolla bootstrap-servers

# Añadido por Pablo. Configuracion de los anillos de Swift
./rings-swift

kolla-ansible -i $INVENTORY --configdir /etc/kolla prechecks
kolla-ansible -i $INVENTORY --configdir /etc/kolla deploy
kolla-ansible post-deploy

# Añadido por Pablo. Configuracion de Trove
./conf-trove
kolla-ansible -i $INVENTORY --configdir /etc/kolla reconfigure -t trove
