#!/bin/bash

if [ ! -z "$1" ]; then
    INVENTORY="/root/kolla/share/kolla-ansible/ansible/inventory/multinode-$1"
else
    INVENTORY="/root/kolla/share/kolla-ansible/ansible/inventory/multinode"
fi

source /root/kolla/bin/activate
kolla-ansible octavia-certificates #Añadido por Pablo
kolla-ansible -i $INVENTORY --configdir /etc/kolla/ bootstrap-servers

# Añadido por David. Solucion del fallo del paquete requests de Python
for i in controller network compute1 compute2 compute3; do ssh $i pip install --force-reinstall requests==2.31.0; done

kolla-ansible -i $INVENTORY --configdir /etc/kolla/ prechecks
kolla-ansible -i $INVENTORY --configdir /etc/kolla/ deploy
kolla-ansible post-deploy
