#!/bin/bash

ssh root@controller << 'EOF'

STORAGE_NODES=(10.0.0.31 10.0.0.32 10.0.0.33)
KOLLA_SWIFT_BASE_IMAGE="kolla/swift-object-expirer:2024.1-ubuntu-jammy"
mkdir -p /etc/kolla/config/swift
chmod -R 777 /etc/kolla/config/swift
mkdir -p /etc/kolla/config/swift/backups
chmod -R 777 /etc/kolla/config/swift/backups

# Create Object Ring
docker run \
  --rm \
  -v /etc/kolla/config/swift/:/etc/kolla/config/swift/ \
  $KOLLA_SWIFT_BASE_IMAGE \
  swift-ring-builder \
    /etc/kolla/config/swift/object.builder create 10 3 1

for node in ${STORAGE_NODES[@]}; do
  for i in {0..2}; do
    docker run \
      --rm \
      -v /etc/kolla/config/swift/:/etc/kolla/config/swift/ \
      $KOLLA_SWIFT_BASE_IMAGE \
      swift-ring-builder \
        /etc/kolla/config/swift/object.builder add r1z1-${node}:6000/swd${i} 1;
  done
done

# Create Account Ring
docker run \
  --rm \
  -v /etc/kolla/config/swift/:/etc/kolla/config/swift/ \
  $KOLLA_SWIFT_BASE_IMAGE \
  swift-ring-builder \
    /etc/kolla/config/swift/account.builder create 10 3 1

for node in ${STORAGE_NODES[@]}; do
  for i in {0..2}; do
    docker run \
      --rm \
      -v /etc/kolla/config/swift/:/etc/kolla/config/swift/ \
      $KOLLA_SWIFT_BASE_IMAGE \
      swift-ring-builder \
        /etc/kolla/config/swift/account.builder add r1z1-${node}:6001/swd${i} 1;
  done
done

# Create Container Ring
docker run \
  --rm \
  -v /etc/kolla/config/swift/:/etc/kolla/config/swift/ \
  $KOLLA_SWIFT_BASE_IMAGE \
  swift-ring-builder \
    /etc/kolla/config/swift/container.builder create 10 3 1

for node in ${STORAGE_NODES[@]}; do
  for i in {0..2}; do
    docker run \
      --rm \
      -v /etc/kolla/config/swift/:/etc/kolla/config/swift/ \
      $KOLLA_SWIFT_BASE_IMAGE \
      swift-ring-builder \
        /etc/kolla/config/swift/container.builder add r1z1-${node}:6002/swd${i} 1;
  done
done

# Rebalance
for ring in object account container; do
  docker run \
    --rm \
    -v /etc/kolla/config/swift/:/etc/kolla/config/swift/ \
    $KOLLA_SWIFT_BASE_IMAGE \
    swift-ring-builder \
      /etc/kolla/config/swift/${ring}.builder rebalance;
done

# # Cambiar permisos de los archivos de configuracion de los anillos
# cd /etc/kolla/config/swift
# chmod 777 container.builder object.builder account.builder

EOF

# Copiar archivos obtenidos al nodo admin
scp -r root@controller:/etc/kolla/config/swift/ /etc/kolla/config/




